# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  python38:
    environment:
      LANG: C.UTF-8
    docker:
      - image: circleci/python:3.8
orbs:
  node: circleci/node@1.1.6
  deepcode: arrai/deepcode@1.1.0
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    environment:
      BASH_ENV: bash_env

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Unit tests
          command: npm test

  deepcode:
    executor: python38
    steps:
      - checkout
      - run:
          name: Install DeepCode CLI
          command: |
            cd ./${CIRCLE_PROJECT_REPONAME}
            python3 -m venv ${HOME}/.venv/
            . ~/.venv/bin/activate
            echo "source ${HOME}/.venv/bin/activate" >> $BASH_ENV
            pip install deepcode
      - run:
          name: Run DeepCode CLI
          command: |
            cd ./${CIRCLE_PROJECT_REPONAME}
            deepcode analyze -txt -p .

workflows:
  version: 2
  dev-build:
    jobs:
      - deepcode/deepcode:
          name: deepcode
          context: arrai-global
          files: "."
          wd: "."
