version: 2.1
orbs:
  deepcode: arrai/deepcode@1.1.0
workflows:
  test:
    jobs:
      - deepcode/deepcode:
          name: deepcode
          context: arrai-global
          files: "."
          wd: "."
          steps:
            - run:
                name: Run DeepCode CLI
                command: |
                  cd <<parameters.wd>>
                  deepcode analyze -sev <<parameters.severity>> -p <<parameters.files>> | tee results.json
