version: 2.1
executors:
  python38:
    environment:
      LANG: C.UTF-8
    docker:
      - image: circleci/python:3.8
jobs:
  deepcode:
    executor: python38
    steps:
      - checkout
      - run:
          name: Install DeepCode CLI
          command: |
            cd ./${CIRCLE_PROJECT_REPONAME}
            python3 -m venv ${HOME}/.venv/
            . ~/.venv/bin/activate
            echo "source ${HOME}/.venv/bin/activate" >> $BASH_ENV
            pip install deepcode
      - run:
          name: Run DeepCode CLI
          command: |
            cd ./${CIRCLE_PROJECT_REPONAME}
            deepcode analyze -txt -p .

workflows:
  version: 2
  orbs:
    deepcode: arrai/deepcode@1.1.0
  workflows:
    test:
      jobs:
        - deepcode/deepcode:
            name: deepcode
            context: arrai-global
            files: "."
            wd: "."
