# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    environment:
      BASH_ENV: bash_env

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Unit tests
          command: npm test

  deploy:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run:
          name: Set AWS credentials
          command: ./node_modules/.bin/sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --overwrite
      - run:
          name: Deploy on AWS
          command: ./deploy.sh "$CIRCLE_BRANCH"

workflows:
  version: 2
  dev-build:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: /(^develop$)|(^master$)/
  dev-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: /develop/
      - deploy:
          requires:
            - build-and-test

  prod-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: /master/
      - deployment-approval:
          type: approval
          requires:
            - build-and-test
      - deploy:
          requires:
            - deployment-approval
