version: 2.1
orbs:
  deepcode: arrai/deepcode@1.1.0
workflows:
  test:
    jobs:
      - deepcode/deepcode:
          name: deepcode
          context: arrai-global
        parameters:
          wd:
            type: string
            default: ./${CIRCLE_PROJECT_REPONAME}
          files:
            type: string
            default: "."
          severity:
            description: "Minimum severity level."
            type: enum
            enum: ["info", "warning", "critical"]
            default: "info"
          steps:
            - run:
                name: Run DeepCode CLI
                command: |
                  cd <<parameters.wd>>
                  deepcode analyze -sev info -p <<parameters.files>> | tee results.json
