version: 2.1
orbs:
  deepcode: arrai/deepcode@1.1.0
workflows:
  test:
    jobs:
      - deepcode/deepcode:
          name: deepcode
          context: arrai-global
          files: "."
          wd: "."
